[package]
name = "tensor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16"
rayon = "1.10"
pyo3 = { version = "0.24", features = ["extension-module"] }
numpy = "0.24"
