[package]
name = "confusion_matrix"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.33"
rayon = "1.10"
pyo3 = { version = "0.24", features = ["extension-module"] }
numpy = "0.24"
