[package]
name = "magnetization"
version = "0.1.0"
edition = "2024"

[lib]
name = "magnetization"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0"
pyo3 = { version = "0.24", features = ["extension-module"] }